// Fixtures de la fiche de prospection, typées sur le contrat OpenAPI généré : si le backend
// ajoute une colonne, ces objets ne compilent plus tant qu'elle n'y figure pas.

import type {
  CaptureBdd,
  InfestationBdd,
  OperationBdd,
  PopulationBdd,
  ProspectionBdd,
} from '@/lib/prospection-fiche-bdd'

/** Fiche dont toutes les colonnes facultatives sont NULL (listes vides pour les listes). */
export function ficheVide(overrides: Partial<ProspectionBdd> = {}): ProspectionBdd {
  return {
    id: 'p1',
    type_prospection: 'intensive',
    campagne_id: 'c1',
    prospecteur_id: 'u1',
    station_id: null,
    n_fiche: null,
    n_message: null,
    date_prospection: '2026-07-10',
    latitude: null,
    longitude: null,
    altitude: null,
    biotope: [],
    surface_station: null,
    surface_prospectee: null,
    surface_infestee: null,
    degats_cultures: null,
    derniere_pluie: null,
    intensite_pluie: null,
    vegetation: null,
    sol: null,
    verdissement: null,
    hauteur_strate: null,
    ennemis_naturels: null,
    observations: null,
    statut: 'brouillon',
    statut_sync: 'local',
    created_at: '2026-07-01T10:00:00Z',
    updated_at: '2026-07-02T08:00:00Z',
    verified_by: null,
    verified_at: null,
    validated_by: null,
    validated_at: null,
    revalide_de_id: null,
    prospecteur_nom: null,
    verified_by_nom: null,
    validated_by_nom: null,
    region: null,
    district: null,
    commune: null,
    za: null,
    pa_code: null,
    degats_cultures_pourcent: null,
    verdissement_pourcent: null,
    hauteur_herbe_cm: null,
    heure_observation_at: null,
    station_libre: null,
    type_station: [],
    verdure_strate: null,
    signalement_source: null,
    signalement_date: null,
    signalement_description: null,
    conclusion_validation: null,
    avertissements: [],
    mode_extensif: null,
    societe: null,
    immatricule_aeronef: null,
    pilote: null,
    mecanicien: null,
    chef_de_base: null,
    base: null,
    base_numero: null,
    base_date_installation: null,
    base_latitude: null,
    base_longitude: null,
    base_secondaire: null,
    base_secondaire_date_installation: null,
    base_secondaire_latitude: null,
    base_secondaire_longitude: null,
    pesticides_embarques: null,
    pesticide_nom_commercial: null,
    pesticide_quantite_disponible: null,
    pesticide_quantite_recue: null,
    futs_disponible: null,
    futs_pleins: null,
    futs_vides: null,
    futs_recues: null,
    signature_visa_nom: null,
    signature_visa_horodatage: null,
    signature_consultant_fao_nom: null,
    signature_consultant_fao_horodatage: null,
    signature_consultant_fao_image: null,
    signature_pilote_nom: null,
    signature_pilote_horodatage: null,
    signature_pilote_image: null,
    signature_chef_base_nom: null,
    signature_chef_base_horodatage: null,
    signature_chef_base_image: null,
    populations: [],
    captures: [],
    infestations: [],
    operations_aeriennes: [],
    ...overrides,
  }
}

export const POPULATION_IMAGO: PopulationBdd = {
  id: 'pop-imago',
  espece: 'LMC',
  categorie: 'imago',
  densite_diffuse: 4,
  densite_groupee: 2,
  captures_nombre: 12,
  temps_capture: 15,
  methode: 'visuel',
  phase: 'solitaire',
  accouplement: 'rare',
  ponte: 'neant',
  captures_sol: 5,
  captures_trans: 3,
  captures_greg: 4,
  stade_imago: 'A3',
  stades_imago: { femelleA1: 3, maleA1: 0 },
  essaim_observe: true,
  densites_larve: null,
  tache_larvaire: null,
  bande_larvaire: null,
  interdistance: null,
  deplacement: null,
  surface_contaminee_ha: null,
  type_cible: ['vol_clair', 'dense'],
  direction_de: 'N',
  direction_vers: 'SE',
  etat: 'repos',
  essaim_en_vol: false,
  essaim_pose: true,
}

export const POPULATION_LARVE: PopulationBdd = {
  id: 'pop-larve',
  espece: 'NSE',
  categorie: 'larve',
  densite_diffuse: null,
  densite_groupee: 8,
  captures_nombre: 6,
  temps_capture: 10,
  methode: 'comptage_direct',
  phase: null,
  accouplement: null,
  ponte: null,
  captures_sol: null,
  captures_trans: null,
  captures_greg: null,
  stade_imago: null,
  stades_imago: null,
  essaim_observe: null,
  densites_larve: { L1: 5, L2: 0 },
  tache_larvaire: true,
  bande_larvaire: false,
  interdistance: 2.5,
  deplacement: 'perchee',
  surface_contaminee_ha: 1.2,
  type_cible: [],
  direction_de: null,
  direction_vers: null,
  etat: null,
  essaim_en_vol: null,
  essaim_pose: null,
}

export const INFESTATION_LARVE: InfestationBdd = {
  id: 'inf-larve',
  espece: 'LMC',
  type_cible: 'tache_larvaire',
  taille_min: 1,
  taille_max: 4,
  taille_moy: 2.5,
  surface_totale: 3.75,
  densite_min: 10,
  densite_max: 90,
  densite_moy: 40.5,
  interdistance: 3,
  comportement: 'repos',
  direction_de: 'O',
  direction_vers: 'E',
  vent_de: 'S',
  vent_vitesse: 4.2,
  pullulation_nb: null,
  taille_long: null,
  taille_large: null,
  taille_epaisseur: null,
  essaim_en_vol: null,
  essaim_pose: null,
  type_essaim: null,
  heure_observation: null,
  densite_en_vol: null,
  dimension_ha: null,
  nb_taches_bandes: 7,
  interdistance_m: 3.5,
  interdistance_min: 1.5,
  interdistance_max: 6,
  interdistance_moy: 3.25,
  surface_contaminee_ha: 2.5,
  type_larve: 'tache_larvaire',
  surface_infestee_pourcent: 12,
  stade_dominant: 'l4_l5',
  taille_groupe_m2: 30,
  front_longueur_m: 20,
  front_largeur_m: 5,
  densite_max_front: 120,
  densite_moy_arriere_front: 60,
}

export const INFESTATION_IMAGO: InfestationBdd = {
  id: 'inf-imago',
  espece: 'NSE',
  type_cible: 'vol_clair',
  taille_min: null,
  taille_max: null,
  taille_moy: null,
  surface_totale: 9,
  densite_min: null,
  densite_max: null,
  densite_moy: 15,
  interdistance: null,
  comportement: 'deplacement',
  direction_de: 'N',
  direction_vers: 'S',
  vent_de: null,
  vent_vitesse: null,
  pullulation_nb: 4,
  taille_long: 100,
  taille_large: 50,
  taille_epaisseur: 10,
  essaim_en_vol: true,
  essaim_pose: false,
  type_essaim: 'vol_clair',
  heure_observation: '07:45',
  densite_en_vol: 250,
  dimension_ha: 3.2,
  nb_taches_bandes: null,
  interdistance_m: null,
  interdistance_min: null,
  interdistance_max: null,
  interdistance_moy: null,
  surface_contaminee_ha: null,
  type_larve: null,
  surface_infestee_pourcent: null,
  stade_dominant: null,
  taille_groupe_m2: null,
  front_longueur_m: null,
  front_largeur_m: null,
  densite_max_front: null,
  densite_moy_arriere_front: null,
}

export const CAPTURES: CaptureBdd[] = [
  { id: 'cap-1', espece: 'LMC', categorie: 'imago', sexe: 'F', phase: 'solitaire', stade: 'A3', effectif: 4 },
  { id: 'cap-2', espece: 'LMC', categorie: 'imago', sexe: 'M', phase: 'gregaire', stade: 'A4', effectif: 3 },
  // Sexe NULL (larve) : ligne bien réelle en base, qu'aucune synthèse ne doit faire disparaître.
  { id: 'cap-3', espece: 'NSE', categorie: 'larve', sexe: null, phase: 'transiens', stade: 'L2', effectif: 9 },
]

export const OPERATION: OperationBdd = {
  id: 'op-1',
  numero: 1,
  type_operation: 'divers',
  motif_divers: 'Convoyage vers la base',
  debut_heure: '06:30',
  debut_temperature_c: 21.5,
  debut_vent_ms: 2,
  fin_heure: '07:15',
  fin_temperature_c: 24,
  fin_vent_ms: 3.5,
  duree_minutes: 45,
}

/** Fiche extensive aérienne dont TOUTES les colonnes portent une valeur non nulle. */
export function ficheComplete(overrides: Partial<ProspectionBdd> = {}): ProspectionBdd {
  return ficheVide({
    type_prospection: 'extensive',
    n_fiche: 'F-001',
    n_message: 'MSG-42',
    station_id: 's1',
    latitude: -18.5,
    longitude: 47.2,
    altitude: 812,
    biotope: ['xerophyle', 'mesophyle'],
    surface_station: 100,
    surface_prospectee: 80,
    surface_infestee: 12.5,
    degats_cultures: 'moyens',
    derniere_pluie: '2026-07-01',
    intensite_pluie: 'forte',
    vegetation: { strates: { herbacee: { recouvrement: 40, hauteur: 0.35 } }, sol_nu: 10 },
    sol: { texture: ['sableux', 'argileux'], humidite: 'sec' },
    verdissement: 30,
    hauteur_strate: 1.5,
    ennemis_naturels: 'Oiseaux',
    observations: 'RAS',
    statut: 'verifiee',
    statut_sync: 'synced',
    verified_by: 'u2',
    verified_at: '2026-07-03T09:00:00Z',
    validated_by: 'u3',
    validated_at: '2026-07-04T09:00:00Z',
    revalide_de_id: 'p0',
    prospecteur_nom: 'Randria Jean',
    verified_by_nom: 'Andria Paul',
    validated_by_nom: 'Rakoto Marie',
    region: 'Menabe',
    district: 'Morondava',
    commune: 'Beroroha',
    za: 'ZA-1',
    pa_code: 'PA-01',
    degats_cultures_pourcent: 15,
    verdissement_pourcent: 40,
    hauteur_herbe_cm: 35,
    heure_observation_at: '2026-07-10T06:45:00Z',
    station_libre: 'Andasibe',
    type_station: ['xerophyle'],
    verdure_strate: 'moyenne',
    signalement_source: 'Chef de village',
    signalement_date: '2026-07-08',
    signalement_description: 'Vol dense signalé au nord',
    conclusion_validation: 'confirmee',
    avertissements: ['Écart important par rapport à la dernière observation.'],
    mode_extensif: 'aerien',
    societe: 'Air Mada',
    immatricule_aeronef: '5R-ABC',
    pilote: 'Jean Rakoto',
    mecanicien: 'Paul Randria',
    chef_de_base: 'Marie Rabe',
    base: 'Base Betioky',
    base_numero: 3,
    base_date_installation: '2026-06-01',
    base_latitude: -23.7,
    base_longitude: 44.4,
    base_secondaire: 'Base Ampanihy',
    base_secondaire_date_installation: '2026-06-15',
    base_secondaire_latitude: -24.7,
    base_secondaire_longitude: 44.7,
    pesticides_embarques: true,
    pesticide_nom_commercial: 'Fyfanon',
    pesticide_quantite_disponible: 600,
    pesticide_quantite_recue: 200,
    futs_disponible: 8,
    futs_pleins: 5,
    futs_vides: 3,
    futs_recues: 2,
    signature_visa_nom: 'Visa Nom',
    signature_visa_horodatage: '2026-07-10T08:00:00Z',
    signature_consultant_fao_nom: 'Consultant Nom',
    signature_consultant_fao_horodatage: '2026-07-10T08:01:00Z',
    signature_consultant_fao_image: 'M0 0 L10 10',
    signature_pilote_nom: 'Pilote Nom',
    signature_pilote_horodatage: '2026-07-10T08:02:00Z',
    signature_pilote_image: 'M0 0 L20 20',
    signature_chef_base_nom: 'Chef Nom',
    signature_chef_base_horodatage: '2026-07-10T08:03:00Z',
    signature_chef_base_image: 'M0 0 L30 30',
    populations: [POPULATION_IMAGO, POPULATION_LARVE],
    captures: CAPTURES,
    infestations: [INFESTATION_LARVE, INFESTATION_IMAGO],
    operations_aeriennes: [OPERATION],
    ...overrides,
  })
}
